replicaCount: 2

image:
  repository: your-dockerhub-username/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  hosts:
    - host: backend.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
