replicaCount: 2

image:
  repository: your-dockerhub-username/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
